const langs: {[ext: string]: string} = {
    ".js": "javascript",
    ".ts": "typescript",
    ".py": "python",
    ".java": "java",
    ".c": "c",
    ".cpp": "c++",
    ".cc": "c++",
    ".h": "c header",
    ".hpp": "c++ header",
    ".cs": "c#",
    ".swift": "swift",
    ".go": "go",
    ".rs": "rust",
    ".kt": "kotlin",
    ".kts": "kotlin script",
    ".dart": "dart",
    ".rb": "ruby",
    ".php": "php",
    ".pl": "perl",
    ".pm": "perl module",
    ".lua": "lua",
    ".m": "objective-c / matlab / octave",
    ".r": "r",
    ".scala": "scala",
    ".hs": "haskell",
    ".fs": "f#",
    ".fsi": "f# interface",
    ".ex": "elixir",
    ".exs": "elixir script",
    ".erl": "erlang",
    ".hrl": "erlang header",
    ".jl": "julia",
    ".sh": "shell script",
    ".bash": "bash",
    ".zsh": "zsh",
    ".ps1": "powershell",
    ".groovy": "groovy",
    ".vbs": "vbscript",
    ".asp": "classic asp",
    ".aspx": "asp.net",
    ".ahk": "autohotkey",
    ".applescript": "applescript",
    ".awk": "awk",
    ".tcl": "tcl",
    ".rexx": "rexx",
    ".cl": "common lisp",
    ".lisp": "lisp",
    ".scm": "scheme",
    ".rkt": "racket",
    ".ml": "ocaml",
    ".mli": "ocaml interface",
    ".pro": "prolog",
    ".p": "prolog",
    ".idc": "idc",
    ".factor": "factor",
    ".forth": "forth",
    ".4th": "forth",
    ".asm": "assembly",
    ".s": "assembly",
    ".nasm": "nasm assembly",
    ".masm": "masm assembly",
    ".vhdl": "vhdl",
    ".v": "verilog",
    ".sv": "systemverilog",
    ".adb": "ada",
    ".ads": "ada specification",
    ".d": "d",
    ".nim": "nim",
    ".cr": "crystal",
    ".hx": "haxe",
    ".idris": "idris",
    ".purs": "purescript",
    ".agda": "agda",
    ".lagda": "literate agda",
    ".lean": "lean",
    ".m2": "macaulay2",
    ".magma": "magma",
    ".wdl": "wdl",
    ".oz": "oz",
    ".ecl": "ecl",
    ".hack": "hack",
    ".pawn": "pawn",
    ".slim": "slim",
    ".vcl": "varnish configuration language",
    ".pwn": "pawn script",
    ".stan": "stan",
    ".tla": "tla+",
    ".json": "json",
    ".json5": "json5",
    ".jsonc": "json with comments",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".ini": "ini",
    ".env": "environment variables",
    ".cfg": "configuration file",
    ".conf": "configuration file",
    ".properties": "java properties",
    ".xml": "xml",
    ".plist": "property list",
    ".html": "html",
    ".htm": "html",
    ".xhtml": "xhtml",
    ".svg": "svg",
    ".xaml": "xaml",
    ".md": "markdown",
    ".markdown": "markdown",
    ".rst": "restructuredtext",
    ".latex": "latex",
    ".tex": "latex",
    ".bib": "bibtex",
    ".rmd": "rmarkdown",
    ".csv": "csv",
    ".tsv": "tsv",
    ".sql": "sql",
    ".psql": "postgresql",
    ".sqlite": "sqlite",
    ".graphql": "graphql",
    ".cypher": "cypher",
    ".sparql": "sparql",
    ".xquery": "xquery",
    ".hql": "hiveql",
    ".pig": "pig latin",
    ".rql": "rethinkdb query language",
    ".q": "q",
    ".sas": "sas",
    ".stata": "stata",
    ".gams": "gams",
    ".gap": "gap",
    ".postscript": "postscript",
    ".ps": "postscript",
    ".gs": "ghostscript",
    ".gcode": "g-code",
    ".scad": "openscad",
    ".stl": "stl",
    ".pov": "pov-ray",
    ".blend": "blender script",
    ".shader": "shaderlab / unity shader",
    ".hlsl": "hlsl",
    ".glsl": "glsl",
    ".vert": "glsl vertex shader",
    ".frag": "glsl fragment shader",
    ".geom": "glsl geometry shader",
    ".tesc": "glsl tessellation control shader",
    ".tese": "glsl tessellation evaluation shader",
    ".comp": "glsl compute shader",
    ".gd": "gdscript",
    ".usf": "unreal shader",
    ".uproject": "unreal project file",
    ".umap": "unreal map file",
    ".tf": "terraform",
    ".hcl": "hcl",
    ".dockerfile": "dockerfile",
    ".makefile": "makefile",
    ".mk": "makefile",
    ".nix": "nix",
    ".bazel": "bazel",
    ".bzl": "bazel",
    ".build": "bazel",
    ".bzlmod": "bazel module",
    ".bicep": "bicep",
    ".rego": "rego",
    ".ebuild": "gentoo ebuild",
    ".eclass": "gentoo eclass",
    ".bp": "blueprint",
    ".cue": "cue",
    ".mcfunction": "minecraft function",
    ".xslt": "xslt",
    ".xsl": "xslt",
    ".mustache": "mustache",
    ".handlebars": "handlebars",
    ".hbs": "handlebars",
    ".mjml": "mjml",
    ".djhtml": "django html",
    ".liquid": "liquid",
    ".cfm": "coldfusion",
    ".cfml": "coldfusion",
    ".ejs": "ejs",
    ".twig": "twig",
    ".nunjucks": "nunjucks",
    ".jinja": "jinja",
    ".haml": "haml",
    ".pug": "pug",
    ".ftl": "freemarker",
    ".dust": "dustjs",
    ".eco": "eco",
    ".eex": "elixir eex",
    ".ecr": "crystal ecr",
    ".tt": "tera",
    ".mtml": "movable type"
}
  

export default langs