# Generated by Django 4.2.6 on 2025-01-26 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FolederName', models.CharField(max_length=32)),
                ('limitedVisibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=32)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(default='Admin', max_length=32)),
                ('isAdmin', models.BooleanField(default=False)),
                ('canCreate', models.BooleanField(default=True)),
                ('canDelete', models.BooleanField(default=True)),
                ('canModifyFiles', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectroles', to='projects.project')),
                ('users', models.ManyToManyField(blank=True, related_name='userRoles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='creatorole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatorole', to='projects.role'),
        ),
        migrations.AddField(
            model_name='project',
            name='defaultrole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultrole', to='projects.role'),
        ),
        migrations.AddField(
            model_name='project',
            name='rootFolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.folder'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='projectsin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('From', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitetokenfrom', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectinvites', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='allowedRoles',
            field=models.ManyToManyField(related_name='roleconnnectedfolders', to='projects.role'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfolders', to='projects.folder'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=32)),
                ('data', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('limitedVisibility', models.BooleanField(default=False)),
                ('filetype', models.CharField(default=None, max_length=32, null=True)),
                ('allowedRoles', models.ManyToManyField(related_name='roleconnnectedfiles', to='projects.role')),
                ('parentFolder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfiles', to='projects.folder')),
            ],
        ),
    ]
