# Generated by Django 4.2.6 on 2025-01-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FolederName', models.CharField(max_length=32)),
                ('parentFolder', models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfolders', to='projects.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=32)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rootFolder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.folder')),
                ('user', models.ManyToManyField(related_name='projectsin', to='Auth.coreuser')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=32)),
                ('data', models.TextField()),
                ('parentFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrenfiles', to='projects.folder')),
            ],
        ),
    ]
