# Generated by Django 5.1.5 on 2025-02-03 03:08

import django.db.models.deletion
import projects.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FolederName', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('limitedVisibility', models.BooleanField(default=False)),
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfolders', to='projects.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=32)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rootFolder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectroot', to='projects.folder')),
                ('user', models.ManyToManyField(related_name='projectsin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('From', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitetokenfrom', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectinvites', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectfolders', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(default='Admin', max_length=32)),
                ('isAdmin', models.BooleanField(default=False)),
                ('canCreate', models.BooleanField(default=True)),
                ('canDelete', models.BooleanField(default=True)),
                ('canModifyFiles', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectroles', to='projects.project')),
                ('users', models.ManyToManyField(blank=True, related_name='userRoles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='creatorole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatorole', to='projects.role'),
        ),
        migrations.AddField(
            model_name='project',
            name='defaultrole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultrole', to='projects.role'),
        ),
        migrations.AddField(
            model_name='folder',
            name='allowedRoles',
            field=models.ManyToManyField(related_name='roleconnnectedfolders', to='projects.role'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parentRoles',
            field=models.ManyToManyField(related_name='rolesofparentfolders', to='projects.role'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=128)),
                ('name', models.CharField(default=models.CharField(max_length=128), max_length=128)),
                ('limitedVisibility', models.BooleanField(default=False)),
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('filetype', models.CharField(default=None, max_length=32, null=True)),
                ('version', models.IntegerField(default=0)),
                ('data', models.FileField(blank=True, default=None, null=True, upload_to=projects.models.get_file_upload_path)),
                ('parentFolder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfiles', to='projects.folder')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('allowedRoles', models.ManyToManyField(related_name='roleconnnectedfiles', to='projects.role')),
                ('parentRoles', models.ManyToManyField(related_name='rolesofparentfiles', to='projects.role')),
            ],
        ),
    ]
