# Generated by Django 4.2.6 on 2025-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
