# Generated by Django 4.2.6 on 2025-01-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parentFolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfiles', to='projects.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parentFolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfolders', to='projects.folder'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rootFolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.folder'),
        ),
    ]
