# Generated by Django 4.2.6 on 2025-01-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creatorole',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defaultrole',
        ),
    ]
