# Generated by Django 4.2.6 on 2025-01-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_creatorole_remove_project_defaultrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creatorole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatorole', to='projects.role'),
        ),
        migrations.AddField(
            model_name='project',
            name='defaultrole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultrole', to='projects.role'),
        ),
    ]
