# Generated by Django 4.2.6 on 2025-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='FileName',
            field=models.CharField(max_length=128),
        ),
    ]
