# Generated by Django 4.2.6 on 2025-01-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_file_parentfolder_alter_folder_parentfolder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parentFolder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfolders', to='projects.folder'),
        ),
    ]
