# Generated by Django 4.2.6 on 2025-01-18 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_creatorole_project_defaultrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='canCreate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='canDelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='canModifyFiles',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('From', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitetokenfrom', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectinvites', to='projects.project')),
            ],
        ),
    ]
