# Generated by Django 4.2.6 on 2025-01-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_folder_parentfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenfolders', to='projects.folder'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='projectsin', to=settings.AUTH_USER_MODEL),
        ),
    ]
