# Generated by Django 5.1.5 on 2025-02-07 06:27

import userConnections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userConnections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(upload_to=userConnections.models.getPath),
        ),
    ]
