# Generated by Django 4.2.6 on 2025-01-22 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userConnections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoingrequestss', to='userConnections.profile')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomingrequestss', to='userConnections.profile')),
            ],
        ),
    ]
