# Generated by Django 4.2.6 on 2025-01-22 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userConnections', '0002_connectionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='incomingrequests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='outgoingrequest',
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoingrequest', to='userConnections.profile'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomingrequests', to='userConnections.profile'),
        ),
    ]
